version: 2.1

jobs:
  loadtest:
    docker:
      - image: cimg/python:3.10  # Use a Python 3.10 Docker image
    steps:
      - checkout  # Check out the code from the repository

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install locust
            pip install faker

      - run:
          name: Run Locust load test
          command: |
            locust -f locustfile.py --headless -u 100 -r 2 --run-time 1m
          no_output_timeout: 10m  # Set a timeout for the load test

      - store_artifacts:
          path: locust_stats.csv  # Save the Locust stats CSV file as an artifact
          destination: locust_stats.csv

      - store_artifacts:
          path: locust_failures.csv  # Save the Locust failures CSV file as an artifact
          destination: locust_failures.csv

workflows:
  version: 2
  loadtest-workflow:
    jobs:
      - loadtest